spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:ewm-dev
    username: postgres
    password: admin
management:
  endpoints.web.exposure.include: loggers
  endpoint.loggers.enabled: true
