stat-server:
  uri: http://localhost:9090

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://stats-db:5432/ewm-stats
    username: postgres
    password: admin
  sql:
    init:
      mode: always